src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_projet;

    #[ORM\Column(type: 'string', length: 255)]
    private $image_projet;

    #[ORM\Column(type: 'string', length: 255)]
    private $link_github;

    #[ORM\Column(type: 'string', length: 255)]
    private $link_extern;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProjet(): ?string
    {
        return $this->nom_projet;
    }

    public function setNomProjet(string $nom_projet): self
    {
        $this->nom_projet = $nom_projet;

        return $this;
    }

    public function getImageProjet(): ?string
    {
        return $this->image_projet;
    }

    public function setImageProjet(string $image_projet): self
    {
        $this->image_projet = $image_projet;

        return $this;
    }

    public function getLinkGithub(): ?string
    {
        return $this->link_github;
    }

    public function setLinkGithub(string $link_github): self
    {
        $this->link_github = $link_github;

        return $this;
    }

    public function getLinkExtern(): ?string
    {
        return $this->link_extern;
    }

    public function setLinkExtern(string $link_extern): self
    {
        $this->link_extern = $link_extern;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $username;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;
    
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/Admin/DashboardController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Project;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;

class DashboardController extends AbstractDashboardController
{
    #[Route('/admin', name: 'admin')]
    public function index(): Response
    {
         return $this->render('dashboard/dashboard.html.twig');
    }

    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setTitle('Portfolio');
    }
    
    public function configureMenuItems(): iterable
    {
        yield MenuItem::linkToDashboard('Dashboard', 'fa fa-home');
        yield MenuItem::linkToCrud('Projects', 'fas fa-list', Project::class);
        // yield MenuItem::linkToCrud('The Label', 'fas fa-list', EntityClass::class);
    }
}

src/Controller/Admin/ProjectCrudController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Project;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;

class ProjectCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Project::class;
    }

    
    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')->hideOnForm(),
            TextField::new('nom_projet'),
            ImageField::new('image_projet')
                ->setBasePath('build/')
                ->setUploadDir('public/build/uploads')
                ->setUploadedFileNamePattern('/uploads/[contenthash].[extension]'),
            TextField::new('link_extern'),
            TextField::new('link_github'),
            TextareaField::new('description'),
        ];
    }
    
}

src/Controller/LoginController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class LoginController extends AbstractController
{
    #[Route('/login', name: 'login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
         $error = $authenticationUtils->getLastAuthenticationError();
    
         // last username entered by the user
         $lastUsername = $authenticationUtils->getLastUsername();
    
         return $this->render('login/login.html.twig', [
             'last_username' => $lastUsername,
             'error'         => $error,
          ]);
    }
    #[Route('/logout', name: 'logout')]
    public function logout(){

    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\ProjectRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    #[Route('/', name: 'main')]
    public function index(ProjectRepository $projectRepository): Response
    {
        $projects = $projectRepository->findAll();
        

        return $this->render('main/index.html.twig',[
            "projects" => $projects
        ]);
    }
}

templates/_partials/_footer.html.twig
<footer id="contact" class="py-5 d-flex justify-content-center">
    <ul>
        <div id="icon-container">
            <a href="#">
                <div class="icon">
                    <li><i class="fab fa-linkedin"></i></li>
                </div>
            </a>
            <a href="#">
                <div class="icon">
                    <li><i class="fab fa-github"></i></li>
                </div>
            </a>
            <a href="#">
                <div class="icon">
                    <li><i class="far fa-envelope"></i></li>
                </div>
            </a>

        </div>
    </ul>
    <div class="separator mt-4"></div>
    <div class="container-fluid d-flex justify-content-center pt-5 text-center text-footer">
        <div class="text-footer row w-100 d-flex justify-content-center">
            <div class="col-4 d-flex justify-content-center">
                <ul>
                    <li> <a href="#">Compétences</a> </li>
                    <li><a href="#">Expérience</a></li>
                    <li><a href="#">Projets</a></li>
                </ul>
            </div>
            <div class="col-4 d-flex justify-content-center">
                <ul>
                    <li> <a href="#">Contact</a></li>
                    <li> <a href="#">A propos</a></li>
                </ul>
            </div>
            <div class="col-4 d-flex justify-content-center">
                <ul>
                    <li> <a href="#">Téléchargez mon CV</a></li>
                    <li> <a href="{{path("login")}}">Panel d'administration</a></li>
                    {% if app.user %}
                        <li> <a href="{{path("logout")}}">Deconnexion</a></li>
                    {% endif %}
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="separator mt-5 w-50"></div>
    <div class="copyright d-flex justify-content-center color-black pt-5">
        Tous droits réservés ©MOULIN Jordan
    </div>
</footer>

templates/_partials/_navbar.html.twig
<nav class="navbar">
  <div class="navLinks">
    <a href="#skill">Compétences</a>
    <a href="#experience">Expériences</a>
    <a href="#project">Mes projets</a>
    <a href="#contactLink" class="contactLink">Contact</a>
  </div>


  <div class="iconLinks">
    <a href="https://github.com/Eldryr62570"><i class="fa-brands fa-github"></i></a>
    <a href=""><i class="fa-brands fa-linkedin"></i></a>
  </div>
  <div class="toggleNight">
    <input type="checkbox" class="checkbox" id="dark-mode" />
    <label for="dark-mode" class="label">
      <i class="fas fa-sun"></i>
      <i class="fas fa-moon"></i>
      <div class="ball"></div>
    </label>
  </div>
</nav>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
    
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
           
        {% endblock %}
                 {{ encore_entry_link_tags('app') }}
        {% block javascripts %}
            
        {% endblock %}
                
    </head>
    <body>
    
        {% block navbar %}
            {% include "_partials/_navbar.html.twig" %}
        {% endblock %}
        {% block body %}
            
        
        {% endblock %}
        {% block footer %} 
            {% include "_partials/_footer.html.twig"%}
        {% endblock %}
        {{ encore_entry_script_tags('app') }}
    </body>
</html>

templates/dashboard/dashboard.html.twig
{% extends "@EasyAdmin/layout.html.twig" %}
{% block content %}
<div>
    <h1>Administration</h1>
    <p> Bienvenue dans l'interface de gestion des projets</p>
</div>
{% endblock %}

templates/login/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('slider') }}
{% endblock %}
{% block body %}
    <div class="form-container py-5">
        <form class="d-flex flex-column align-items-center" action="{{ path('login') }}"  method="post">
            <div class="form-group">
                <input type="text"  name="_username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    placeholder="Pseudo">
            </div>
            <div class="form-group">
                <input type="password" name="_password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    placeholder="Mot de passe">
            </div>
            <input type="hidden" name="_target_path" value="/admin"/> 
            <div class="d-flex justify-content-start w-100">
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Portfolio{% endblock %}

{% block body %}
<a id="button"></a>
<section class="titleBody">
    <div class="container-fluid h-100 g-0">
        <div class="row h-100 g-0">
            <div class="col-lg-7">
                <div class="h-50 d-flex align-items-center">
                    <h1><span>M</span>oulin Jordan</h1>
                </div>
                <div class="h-50">
                    <p class="display-6">Développeur Web et Web mobile,</p>
                    <p class="display-6">Orienté "Backend/Full stack".</p>
                    <a href="{{asset("build/uploads/CV_MOULIN_Jordan_Developpeur_web.pdf")}}" download="CV_MOULIN_Jordan_Developpeur_web.pdf" class="btn btn-custom1">Télécharger mon CV <i class="fa-solid fa-download"></i></a>
                </div>
            </div>
            <div class="col-lg-5 d-flex justify-align-center align-items-center ml-5">
                <div class="profilePicture d-flex justify-content-center align-items-center"></div>
            </div>
        </div>
    </div>
</section>
<section class="skills" id="skill">
    <div class="titleContainer">
        <div class="display-2 p-5">
            <span>C</span>ompétences
        </div>
    </div>
    <div class="w-100 h-100 d-flex align-items-center my-5">
        <div class="container-fluid">
            <div class="row p-5">
                <div class="col d-flex justify-content-center p-1">
                    <div class="card bg-light mb-3" style="max-width: 18rem;">
                        <div class="card-header text-center display-3 align-items-center color-bg-grey"><i
                                class="fa-brands fa-html5 color-html"></i>&nbsp;&nbsp;<i
                                class="fa-brands fa-css3-alt color-css"></i></div>
                        <div class="card-body color-bg-white">
                            <h5 class="card-title d-flex justify-content-center">Html&nbsp;/&nbsp;CSS</h5>
                            <p class="card-text">Language de balisage Html Language de style css</p>
                        </div>
                    </div>
                </div>
                <div class="col d-flex justify-content-center p-1">
                    <div class="card bg-light mb-3" style="max-width: 18rem;">
                        <div class="card-header text-center display-3 align-items-center color-bg-grey"><i
                                class="fa-brands fa-js color-js"></i></div>
                        <div class="card-body color-bg-white js">
                            <h5 class="card-title d-flex justify-content-center ">Javascript</h5>
                            <p class="card-text">Javascript "FrontEnd" / "BackEnd"</p>
                        </div>
                    </div>
                </div>

                <div class="col d-flex justify-content-center p-1">
                    <div class="card bg-light mb-3" style="max-width: 18rem;">
                        <div class="card-header text-center display-3 align-items-center color-bg-grey"><i
                                class="fa-brands fa-php color-php"></i></div>
                        <div class="card-body color-bg-white">
                            <h5 class="card-title d-flex justify-content-center">PHP</h5>
                            <p class="card-text">PHP natif / POO / MVC</p>
                        </div>
                    </div>
                </div>
                <div class="col d-flex justify-content-center p-1">
                    <div class="card bg-light mb-3" style="max-width: 18rem;">
                        <div class="card-header text-center display-3 align-items-center color-bg-grey"><i
                                class="fa-brands fa-symfony"></i>&nbsp;&nbsp;<i class="fa-brands fa-laravel"></i></div>
                        <div class="card-body color-bg-white">
                            <h5 class="card-title d-flex justify-content-center  ">Framework Symfony / Laravel</h5>
                            <p class="card-text">Framework php Symfony et Laravel</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<section class="exp" id="experience">
    <div class="titleContainer">
        <div class="display-2 p-5">
            <span>E</span>xpériences
        </div>
    </div>
    <div class="exp-container">
        <div class="title-exp display-5">Formation Simplon développeur web (Charleville-mézières)</div>
        <div class="text-exp">
            2021/2022
        </div>
        <div class="title-exp display-5">Licence Informatique (Reims)</div>
        <div class="text-exp">
            2019/2021
        </div>
        <div class="title-exp display-5">Prépa CPGE TSI (Valenciennes)</div>
        <div class="text-exp">
            2017/2019
        </div>
        <div class="title-exp display-5">BAC STI2D option SIN</div>
        <div class="text-exp">
            2016/2017
        </div>

    </div>
</section>

<section class="skills pt-5">
    <div class="titleContainer">
        <div class="display-2 p-5">
            <span>M</span>es projets
        </div>
    </div>
    {% for project in projects %}
    <div class="w-100 h-100 d-flex align-items-center my-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col d-flex justify-content-center p-1">
                    <div class="card bg-light mb-3" style="max-width: 18rem;">
                        <div class="card-header text-center display-3 align-items-center color-bg-grey">
                            <img src="build/{{ project.imageProjet }}" alt="" class="img-fluid rounded">
                        </div>
                        <div class="card-body color-bg-white">
                            <h5 class="card-title d-flex justify-content-center display-6 pb-4">{{ project.nomProjet }}
                            </h5>
                            <p class="card-text text-center">{{ project.description}}</p>
                            <div class="iconContainer d-flex justify-content-around w-50 py-3">
                                <a href="{{ project.linkGithub }}"><i class="fa-brands fa-github"></i></a>
                                <a href="{{ project.linkExtern }}"><i class="fa-solid fa-link"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}



</section>
<section class="form-contact" id="contactLink">
    <div class="titleContainer-blue">
        <div class="display-2 pt-5 pb-3 ml-5 title-contact">
            <span>C</span>ontact
        </div>
        <div class="title-desc">
            Formulaire de contact via e-mail
        </div>
    </div>
    <div class="form-container py-5">
        <form class="d-flex flex-column align-items-center">
            <div class="form-group">
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    placeholder="Nom">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    placeholder="Prénom">
            </div>
            <div class="form-group">
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    placeholder="E-mail">
            </div>
            <div class="form-group">
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="4"
                    placeholder="Message"></textarea>
            </div>
            <div class="d-flex justify-content-start w-100">
                <button type="submit" class="btn btn-primary">Envoyer</button>
            </div>
        </form>
    </div>
</section>

{% endblock %}